# Generated by Django 6.0.4 on 2026-05-05 13:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('emergency_contact_name', models.CharField(max_length=255)),
                ('emergency_contact_phone', models.CharField(max_length=15)),
                ('id_proof_type', models.CharField(choices=[('aadhaar', 'Aadhaar'), ('passport', 'Passport'), ('voter_id', 'Voter ID'), ('driving_license', 'Driving License')], max_length=30)),
                ('id_proof_number', models.CharField(max_length=50)),
                ('id_proof_url', models.URLField(blank=True, null=True)),
                ('advance_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rent_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rent_due_day', models.IntegerField(default=1)),
                ('joining_date', models.DateField()),
                ('expected_leaving_date', models.DateField(blank=True, null=True)),
                ('actual_leaving_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('notice_period', 'Notice Period'), ('vacated', 'Vacated')], default='active', max_length=20)),
                ('police_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant', to='pgs.bed')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='pgs.property')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenants', to='pgs.room')),
            ],
        ),
    ]
